<?php
/**
 * Implements hook_form_views_exposed_form_alter().
 */
function gsb_filtered_view_link_form_views_exposed_form_alter(&$form, &$form_state) {
  global $user;
  if ($user->uid == 1 || array_intersect(array('section manager', 'marketing_admin', 'administrator'), array_values($user->roles))) {
    drupal_add_js(drupal_get_path('module', 'gsb_filtered_view_link') . '/js/gsb_filtered_view_link.js');
  }
}